/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 14
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COMMA = 1,
  anon_sym_SEMI = 2,
  sym_macro = 3,
  sym_comment = 4,
  sym_number = 5,
  aux_sym_class_name_token1 = 6,
  sym_source_file = 7,
  sym_object = 8,
  sym_class_name = 9,
  sym__value = 10,
  sym_string = 11,
  aux_sym_source_file_repeat1 = 12,
  aux_sym_object_repeat1 = 13,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [sym_macro] = "macro",
  [sym_comment] = "comment",
  [sym_number] = "number",
  [aux_sym_class_name_token1] = "class_name_token1",
  [sym_source_file] = "source_file",
  [sym_object] = "object",
  [sym_class_name] = "class_name",
  [sym__value] = "_value",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_object_repeat1] = "object_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_macro] = sym_macro,
  [sym_comment] = sym_comment,
  [sym_number] = sym_number,
  [aux_sym_class_name_token1] = aux_sym_class_name_token1,
  [sym_source_file] = sym_source_file,
  [sym_object] = sym_object,
  [sym_class_name] = sym_class_name,
  [sym__value] = sym__value,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_object_repeat1] = aux_sym_object_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_macro] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_class_name_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_class_name] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_class = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_class] = "class",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_class, 0},
  [1] =
    {field_class, 0},
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '!') ADVANCE(8);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead == ',') ADVANCE(4);
      if (lookahead == '.') ADVANCE(15);
      if (lookahead == ';') ADVANCE(5);
      if (('+' <= lookahead && lookahead <= '-')) ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '!') ADVANCE(8);
      if (lookahead == '#') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_macro);
      if (lookahead == '!' ||
          lookahead == ',' ||
          lookahead == ';') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_macro);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_class_name_token1);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_class_name_token1);
      if (lookahead == '.') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_class_name_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          (lookahead < '+' || '-' < lookahead) &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_class_name_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_class_name_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_class_name_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '!' &&
          lookahead != ',' &&
          lookahead != ';') ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 2},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_macro] = ACTIONS(3),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(1),
    [aux_sym_class_name_token1] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(19),
    [sym_object] = STATE(4),
    [sym_class_name] = STATE(11),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_macro] = ACTIONS(3),
    [sym_comment] = ACTIONS(3),
    [aux_sym_class_name_token1] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__value] = STATE(6),
    [sym_string] = STATE(6),
    [aux_sym_object_repeat1] = STATE(7),
    [anon_sym_COMMA] = ACTIONS(9),
    [anon_sym_SEMI] = ACTIONS(11),
    [sym_macro] = ACTIONS(3),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(13),
    [aux_sym_class_name_token1] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__value] = STATE(15),
    [sym_string] = STATE(15),
    [anon_sym_COMMA] = ACTIONS(17),
    [anon_sym_SEMI] = ACTIONS(17),
    [sym_macro] = ACTIONS(3),
    [sym_comment] = ACTIONS(3),
    [sym_number] = ACTIONS(19),
    [aux_sym_class_name_token1] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(7), 1,
      aux_sym_class_name_token1,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_class_name,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
    STATE(5), 2,
      sym_object,
      aux_sym_source_file_repeat1,
  [18] = 5,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      aux_sym_class_name_token1,
    STATE(11), 1,
      sym_class_name,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
    STATE(5), 2,
      sym_object,
      aux_sym_source_file_repeat1,
  [36] = 4,
    ACTIONS(9), 1,
      anon_sym_COMMA,
    ACTIONS(28), 1,
      anon_sym_SEMI,
    STATE(8), 1,
      aux_sym_object_repeat1,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
  [50] = 4,
    ACTIONS(9), 1,
      anon_sym_COMMA,
    ACTIONS(30), 1,
      anon_sym_SEMI,
    STATE(9), 1,
      aux_sym_object_repeat1,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
  [64] = 4,
    ACTIONS(9), 1,
      anon_sym_COMMA,
    ACTIONS(32), 1,
      anon_sym_SEMI,
    STATE(9), 1,
      aux_sym_object_repeat1,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
  [78] = 4,
    ACTIONS(34), 1,
      anon_sym_COMMA,
    ACTIONS(37), 1,
      anon_sym_SEMI,
    STATE(9), 1,
      aux_sym_object_repeat1,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
  [92] = 2,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [101] = 3,
    ACTIONS(41), 1,
      anon_sym_COMMA,
    ACTIONS(43), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
  [112] = 3,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      aux_sym_class_name_token1,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
  [123] = 3,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      aux_sym_class_name_token1,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
  [134] = 2,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
    ACTIONS(53), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [143] = 2,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
    ACTIONS(37), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [152] = 3,
    ACTIONS(55), 1,
      ts_builtin_sym_end,
    ACTIONS(57), 1,
      aux_sym_class_name_token1,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
  [163] = 3,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      aux_sym_class_name_token1,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
  [174] = 3,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      aux_sym_class_name_token1,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
  [185] = 2,
    ACTIONS(67), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_macro,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 18,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 50,
  [SMALL_STATE(8)] = 64,
  [SMALL_STATE(9)] = 78,
  [SMALL_STATE(10)] = 92,
  [SMALL_STATE(11)] = 101,
  [SMALL_STATE(12)] = 112,
  [SMALL_STATE(13)] = 123,
  [SMALL_STATE(14)] = 134,
  [SMALL_STATE(15)] = 143,
  [SMALL_STATE(16)] = 152,
  [SMALL_STATE(17)] = 163,
  [SMALL_STATE(18)] = 174,
  [SMALL_STATE(19)] = 185,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 1, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_name, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 2, 0, 1),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 2, 0, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 3, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 3, 0, 1),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 2),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 4, 0, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 4, 0, 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 4, 0, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 5, 0, 2),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object, 5, 0, 2),
  [67] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_idf(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "idf",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
